### ISSUE TITLE
7.23 问题总结&改进方向

### ISSUE THREAD

**Issue by tremblestarman** [CommandBlockLogic/exploding-sheep#3]
重新思考了游戏过程中的问题，基于远古的测试
提供了一些解决方法，并非最终论调，但尽量减少工作量
以下本游戏简称es

----

### 问题

- 攻守不平

守方可受攻方攻击范围太大（地图开放到没有防守掩体），可以说四面受敌，故造成攻守不平衡。参考传统fps、moba等类型游戏的攻守模式，守方首先要占据优势，不只是主观机制上的优势（主要是占领点的cd恢复和无敌，这一点es也有类似），也有客观场景游戏（比如多数游戏中的大量掩体，防御设施，封闭空间等）

### 方案

为守方提供有利场景，比如沙的摆放方式，更多掩体，以及解除攻方制高点优势等

### 问题

- 战斗方式单一
es并非传统fps，相当于蓄蓝射击的魔法游戏，cd过长容易形成回合制，应该适当鼓励使用其他羊和其他攻击方式

- 辅助元素缺少
目前只是注重了射击，但缺少了辅助元素，让es看起来只是一款操作困难的纯fps游戏，可玩内容因此也就缺乏了。可参考以前CBL崛起时期（15年初）的几个作品，依靠道具来丰富内容，但es无需走这条路，可以在职业上做些修改

### 方案
主要可以在职业上稍作改变，增加内容不多

- 战斗方式
黑羊，正常战斗时没什么用，因此可以在瞬移后允许玩家限时使用高威力近身武器为其添加辅助功能；红羊，急爆，实际上对高走位也没太大作用，不妨同时添加小范围减益效果或者爆炸溅射黄羊，由于扇子而且后期会减速也显得多余，不如减小碰撞体积同时用于对付蜷缩玩家比如使其失重；其他等等往后再讨论

- 辅助元素
主要是针对职业的增益效果，可以是人畜无害同时实现简单的小幅药水效果增益（比如缓降，速度等），也可以花些功夫在玩家所穿着的那双鞋子上（比如生命上限，抗击退等）
总之丰富职业内容，至于平衡问题没有那么麻烦，先按照计划丰富战斗方式，主要靠后期对职业生命调整来制约职业间因战斗方式造成的差异。
----
# 总结
总结一下，现在之所以感觉无聊就是太单一，之所以难平衡也是太单一，游戏机制没有形成网状调控的关系让现在的我们感觉无思路可走。现在的做法就是想办法用不太费劲的方式，主要靠mc自带的游戏机制把水搅浑，创造一个可调控的关系，以此来发展新思路

**Comment by K-bai** [comment]
好 我来填坑了
